version: "3.8"

services:
  server:
    image: bloglist-back
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    environment:
      - PORT=3003
      - MONGODB_URI=mongodb+srv://ariful6:Ariful123@cluster0.tceqdtd.mongodb.net/blogApp?retryWrites=true&w=majority
      - TEST_MONGODB_URI = mongodb+srv://ariful6:Ariful123@cluster0.tceqdtd.mongodb.net/testBlogApp?retryWrites=true&w=majority
      - SECRET=secret
    container_name: bloglist-back

  app:
    image: bloglist-front
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api/
    container_name: bloglist-front
    depends_on:
      - server

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - server
      - app
